const dummyData = [{
	"url": "https://api.miami211.openreferral.org/index.php",
	"label": "Miami Services - Live",
	"organisationLabel": "Miami Open211 Project",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T15:53:26",
	"checkIsRunning": false,
	"timeTaken": 21832,
	"isUp": false,
	"isServicesValid": false,
	"servicesMessage": "",
	"isServiceExampleValid": false,
	"serviceExampleIdentifier": "",
	"serviceExampleMessage": "",
	"isSearchEnabled": false,
	"searchEnabledMessage": ""
}, {
	"url": "https://api.porism.com/ServiceDirectoryServiceBlackburn",
	"label": "Blackburn Services - Sample data",
	"organisationLabel": "Porism",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T15:54:09",
	"checkIsRunning": false,
	"timeTaken": 1038962,
	"isUp": true,
	"isServicesValid": true,
	"servicesMessage": "",
	"isServiceExampleValid": false,
	"serviceExampleIdentifier": "20fa9eb4-acac-4856-8b7e-62853be903d6",
	"serviceExampleMessage": "Time Search Test failed. When tested using /services?start_time=19%3a30%3a00\u0026end_time=21%3a00%3a00\u0026day=MO\nPostcode Search failed. When tested using /services?proximity=100\u0026postcode=BB2\u002B6PS",
	"isSearchEnabled": false,
	"searchEnabledMessage": "Time Search Test failed. When tested using /services?start_time=19%3a30%3a00\u0026end_time=21%3a00%3a00\u0026day=MO\nPostcode Search failed. When tested using /services?proximity=100\u0026postcode=BB2\u002B6PS"
}, {
	"url": "https://api.porism.com/ServiceDirectoryServiceCQC",
	"label": "Care Quality Commission",
	"organisationLabel": "Porism",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T16:11:32",
	"checkIsRunning": false,
	"timeTaken": 271160,
	"isUp": true,
	"isServicesValid": true,
	"servicesMessage": "",
	"isServiceExampleValid": true,
	"serviceExampleIdentifier": "00a1a2df-9284-415a-b1db-e2d5e4b035ad",
	"serviceExampleMessage": "",
	"isSearchEnabled": true,
	"searchEnabledMessage": ""
}, {
	"url": "https://api.porism.com/ServiceDirectoryServiceElmbridge",
	"label": "Elmbridge Services - UAT",
	"organisationLabel": "Placecube",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T16:38:16",
	"checkIsRunning": false,
	"timeTaken": 1935,
	"isUp": true,
	"isServicesValid": true,
	"servicesMessage": "",
	"isServiceExampleValid": true,
	"serviceExampleIdentifier": "095f02dc-d9ea-44e9-8a23-02b83a20e18d",
	"serviceExampleMessage": "Time Search Test failed. When tested using /services?start_time=09%3a00%3a00\u0026end_time=17%3a00%3a00\u0026day=FR",
	"isSearchEnabled": false,
	"searchEnabledMessage": "Time Search Test failed. When tested using /services?start_time=09%3a00%3a00\u0026end_time=17%3a00%3a00\u0026day=FR"
}, {
	"url": "https://api.porism.com/ServiceDirectoryServiceNYorks",
	"label": "North Yorkshire SevicesData at 20/12/2019",
	"organisationLabel": "Porism",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T16:27:40",
	"checkIsRunning": false,
	"timeTaken": 519838,
	"isUp": true,
	"isServicesValid": true,
	"servicesMessage": "",
	"isServiceExampleValid": true,
	"serviceExampleIdentifier": "0a75e2f4-c35d-4c89-b854-8ca642588b7a",
	"serviceExampleMessage": "",
	"isSearchEnabled": true,
	"searchEnabledMessage": ""
}, {
	"url": "https://api.porism.com/ServiceDirectoryServiceOpenActiveAggregated",
	"label": "OpenActive Sports \u0026 Wellbeing Services - Aggregated feed (Porism)",
	"organisationLabel": "Porism",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T16:38:35",
	"checkIsRunning": false,
	"timeTaken": 203342,
	"isUp": true,
	"isServicesValid": true,
	"servicesMessage": "",
	"isServiceExampleValid": true,
	"serviceExampleIdentifier": "006e8c7a-1cf4-4904-bb91-751def2ee02d",
	"serviceExampleMessage": "Postcode Search failed. When tested using /services?proximity=100\u0026postcode=IP5\u002B2EN",
	"isSearchEnabled": false,
	"searchEnabledMessage": "Postcode Search failed. When tested using /services?proximity=100\u0026postcode=IP5\u002B2EN"
}, {
	"url": "https://bristol.openplace.directory/o/ServiceDirectoryService/v2",
	"label": "Bristol Services - Live",
	"organisationLabel": "Placecube",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T16:44:48",
	"checkIsRunning": false,
	"timeTaken": 832,
	"isUp": true,
	"isServicesValid": false,
	"servicesMessage": "A paginatable service method is not present. Of the form /services?page={nn}",
	"isServiceExampleValid": false,
	"serviceExampleIdentifier": "",
	"serviceExampleMessage": "",
	"isSearchEnabled": false,
	"searchEnabledMessage": ""
}, {
	"url": "https://lgaapi.connecttosupport.org",
	"label": "Hull Services - Live",
	"organisationLabel": "PCG",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T16:48:54",
	"checkIsRunning": false,
	"timeTaken": 5154,
	"isUp": true,
	"isServicesValid": false,
	"servicesMessage": "Missing search method paginaton metadata at the begining of the JSON payload it should be in the following format: {\u0022totalElements\u0022:nn,\u0022totalPages\u0022:nn,\u0022number\u0022:nn,\u0022size\u0022:nn,\u0022first\u0022:bb,\u0022last\u0022:bb\u0022,\u0022content\u0022:[{},{}]",
	"isServiceExampleValid": true,
	"serviceExampleIdentifier": "42f2e71e-de61-418b-b9b7-ab5200fed901",
	"serviceExampleMessage": "Text Test failed. When tested using /services?text=History\u002BCentre.",
	"isSearchEnabled": false,
	"searchEnabledMessage": "Text Test failed. When tested using /services?text=History\u002BCentre."
}, {
	"url": "https://outpost-api-service.herokuapp.com/api/v1",
	"label": "Buckinghamshire Family Information Service",
	"organisationLabel": "FutureGov",
	"organisationUrl": "",
	"servicePathOverride": "",
	"lastCheck": "2021-05-25T16:49:07",
	"checkIsRunning": false,
	"timeTaken": 103955,
	"isUp": false,
	"isServicesValid": false,
	"servicesMessage": "",
	"isServiceExampleValid": false,
	"serviceExampleIdentifier": "",
	"serviceExampleMessage": "",
	"isSearchEnabled": false,
	"searchEnabledMessage": ""
}];

export default dummyData;
