const mockData = [
    {
        "url": "https://api.porism.com/ServiceDirectoryServiceBlackburn",
        "label": "Blackburn Services - Sample data (Porism)",
        "organisationLabel": "Blackburn with Darwen Borough Council",
        "organisationUrl": "https://www.blackburn.gov.uk/",
        "developerLabel": "Porism",
        "developerUrl": "https://porism.com/",
        "servicePathOverride": "",
        "lastCheck": "2021-05-27T13:23:58",
        "checkIsRunning": false,
        "timeTaken": 3138,
        "isUp": true,
        "isServicesValid": true,
        "servicesMessage": "",
        "isServiceExampleValid": true,
        "serviceExampleIdentifier": "0fa70aed-b3f9-4cb0-a4f8-be51b0fe0e31",
        "serviceExampleMessage": "",
        "isSearchEnabled": true,
        "searchEnabledMessage": ""
    },
    {
        "url": "https://api.porism.com/ServiceDirectoryServiceCQC",
        "label": "Care Quality Commission (Porism)",
        "organisationLabel": "Care Quality Commission",
        "organisationUrl": "",
        "developerLabel": "Porism",
        "developerUrl": "https://porism.com/",
        "servicePathOverride": "",
        "lastCheck": "2021-05-28T17:23:13",
        "checkIsRunning": false,
        "timeTaken": 40459,
        "isUp": true,
        "isServicesValid": true,
        "servicesMessage": "",
        "isServiceExampleValid": true,
        "serviceExampleIdentifier": "03768861-41bb-49da-99bc-d31f85598433",
        "serviceExampleMessage": "",
        "isSearchEnabled": true,
        "searchEnabledMessage": ""
    },
    {
        "url": "https://api.porism.com/ServiceDirectoryServiceElmbridge",
        "label": "Elmbridge Services - UAT (Placecube)",
        "organisationLabel": "Elmbridge Borough Council",
        "organisationUrl": "https://www.elmbridge.gov.uk/",
        "developerLabel": "Placecube",
        "developerUrl": "https://www.placecube.com/",
        "servicePathOverride": "",
        "lastCheck": "2020-05-28T13:36:29",
        "checkIsRunning": false,
        "timeTaken": 1246,
        "isUp": true,
        "isServicesValid": true,
        "servicesMessage": "",
        "isServiceExampleValid": true,
        "serviceExampleIdentifier": "00ddbec5-a968-491c-801f-7ca216c599f1",
        "serviceExampleMessage": "Time Search Test failed. When tested using /services?start_time=10%3a00%3a00&end_time=00%3a00%3a00&day=TH",
        "isSearchEnabled": false,
        "searchEnabledMessage": "Time Search Test failed. When tested using /services?start_time=10%3a00%3a00&end_time=00%3a00%3a00&day=TH"
    },
    {
        "url": "https://api.porism.com/ServiceDirectoryServiceNYorks",
        "label": "North Yorkshire SevicesData at 20/12/2019 (Porism)",
        "organisationLabel": "North Yorkshire County Council",
        "organisationUrl": "https://www.northyorks.gov.uk/",
        "developerLabel": "Porism",
        "developerUrl": "https://porism.com/",
        "servicePathOverride": "",
        "lastCheck": "2021-06-01T09:29:37",
        "checkIsRunning": false,
        "timeTaken": 5820,
        "isUp": true,
        "isServicesValid": true,
        "servicesMessage": "",
        "isServiceExampleValid": true,
        "serviceExampleIdentifier": "05c55e1c-7775-4904-8398-94e949891db5",
        "serviceExampleMessage": "",
        "isSearchEnabled": true,
        "searchEnabledMessage": ""
    },
    {
        "url": "https://api.porism.com/ServiceDirectoryServiceOpenActiveAggregated",
        "label": "OpenActive Sports &amp; Wellbeing",
        "organisationLabel": "OpenActive Sports & Wellbeing",
        "organisationUrl": "",
        "developerLabel": "Porism",
        "developerUrl": "https://porism.com/",
        "servicePathOverride": "",
        "lastCheck": "2021-05-28T17:13:30",
        "checkIsRunning": false,
        "timeTaken": 30301,
        "isUp": true,
        "isServicesValid": true,
        "servicesMessage": "",
        "isServiceExampleValid": true,
        "serviceExampleIdentifier": "009371c1-a6e3-43ee-b699-f84a7c911cb4",
        "serviceExampleMessage": "Postcode Search failed. When tested using /services?proximity=100&postcode=GU10+4HU",
        "isSearchEnabled": false,
        "searchEnabledMessage": "Postcode Search failed. When tested using /services?proximity=100&postcode=GU10+4HU"
    },
    {
        "url": "https://bristol.openplace.directory/o/ServiceDirectoryService/v2",
        "label": "Bristol Services - Live (Placecube)",
        "organisationLabel": "Bristol City Council",
        "organisationUrl": "https://www.bristol.gov.uk/",
        "developerLabel": "Placecube",
        "developerUrl": "https://www.placecube.com/",
        "servicePathOverride": "",
        "lastCheck": "2021-05-28T17:20:38",
        "checkIsRunning": false,
        "timeTaken": 27254,
        "isUp": true,
        "isServicesValid": true,
        "servicesMessage": "",
        "isServiceExampleValid": true,
        "serviceExampleIdentifier": "8e434bf2-2c8f-df3c-b6e8-16127fe78c0f",
        "serviceExampleMessage": "",
        "isSearchEnabled": true,
        "searchEnabledMessage": ""
    },
    {
        "url": "https://lgaapi.connecttosupport.org",
        "label": "Hull Services - Live (PCG)",
        "organisationLabel": "Hull City Council",
        "organisationUrl": "http://www.hull.gov.uk/",
        "developerLabel": "PCG",
        "developerUrl": "https://www.publicconsultinggroup.co.uk/",
        "servicePathOverride": "",
        "lastCheck": "2021-05-28T17:21:39",
        "checkIsRunning": false,
        "timeTaken": 5834,
        "isUp": true,
        "isServicesValid": false,
        "servicesMessage": "Missing search method paginaton metadata at the begining of the JSON payload it should be in the following format: {\"totalElements\":nn,\"totalPages\":nn,\"number\":nn,\"size\":nn,\"first\":bb,\"last\":bb\",\"content\":[{},{}]",
        "isServiceExampleValid": true,
        "serviceExampleIdentifier": "be7c22cc-a661-4116-88ad-ab2100ab199e",
        "serviceExampleMessage": "Text Test failed. When tested using /services?text=Nelly%27s+Knitting+Group+Test",
        "isSearchEnabled": false,
        "searchEnabledMessage": "Text Test failed. When tested using /services?text=Nelly%27s+Knitting+Group+Test"
    },
    {
        "url": "https://outpost-api-service.herokuapp.com/api/v1",
        "label": "Buckinghamshire Family Information Service - (FutureGov)",
        "organisationLabel": "Buckinghamshire Council",
        "organisationUrl": "https://www.buckinghamshire.gov.uk/",
        "developerLabel": "FutureGov",
        "developerUrl": "https://wearefuturegov.com/",
        "servicePathOverride": "",
        "lastCheck": "2021-05-26T13:33:26",
        "checkIsRunning": false,
        "timeTaken": 121885,
        "isUp": true,
        "isServicesValid": false,
        "servicesMessage": "A paginatable service method is not present. Of the form /services?page={nn}",
        "isServiceExampleValid": false,
        "serviceExampleIdentifier": "",
        "serviceExampleMessage": "",
        "isSearchEnabled": false,
        "searchEnabledMessage": ""
    }
];

export default mockData;